### ISSUE TITLE
App concept?

### ISSUE THREAD

**Issue by BTBTravis** [redi-js-teachers/js_sprint_2020_final_project_stankasvecova#1]
Hey @stankasvecova lets keep track of your app concept here. 

I'm going to attempt and summarize my understanding thus far.

- A portal website collecting content made by teenagers for teenagers. 
- Inspirational content, organized as various 'hobbies'.
- A place for teens from around the world to share and connect

## Functionality

- Registration and user account system (**priority 1**)
- User profile system
- Video Blocks for externally hosted videos, with commenting and description (**priority 1**)
- Video Block likes system
  - likes = 🍦, dislikes = 🐸 (priority 3)
- Video Block tagging (priority 3)
  - tags are 'hobbies'
- Blogs / Text Story Blocks (priority 3)
- Photo Blocks (priority 3)
- Job section: adverts taken from third-parties websites, collected in the jobs. section of the site (priority 2)
- Clubs: 'groups' that one can join for a fee (an online book-club, an online tech club, an online art club, connected by zoom weekly meetings) (priority 2)
- Chat. A regular forum (priority 2)

## Screenshots

_Hobbies sub-pages in a vertical nav:_

![good_teens_002](https://user-images.githubusercontent.com/13404719/82487565-d084c200-9ade-11ea-92e1-5b8402676741.png)

_Registration Form:_

![good_teens_001](https://user-images.githubusercontent.com/13404719/82487560-cf539500-9ade-11ea-9988-b9fcb99b0751.png)

![good_teens_003](https://user-images.githubusercontent.com/13404719/82487570-d24e8580-9ade-11ea-951b-d6e9ccf13300.png)

**Comment by BTBTravis** [comment]
Great work on coming up with an idea @stankasvecova! I dig it. As @MrTim mentioned there is quite a lot of things to be done and any one of them would probably be enough for a final project. So lets figure out what you want to work of first. 

I see you have some topic marked as priority 1. We could start with them or whichever part you are most motivated about. 

So which feature would you like to start with?

**Comment by stankasvecova** [comment]
Hey Travis, great summary above! Thanks for that.

Yes, according to the priorities, I think it makes sense to start with:
1. Registration
2. User account
3. Video-upload functionality

I don't know if all three are doable in a month? What do you think?
I have started little bit with the registration, but I have no idea how difficult the user account and video-upload functionality will be!

Thanks

**Comment by MrTim** [comment]
Hey-hey,
This list look ok. We can do it in the following way: focus on registration and user account page and then if still have time we try video upload.
For registration part we would need external provider. As I mentioned I know how to do it with google OAuth + FireBase and React. Should be nearly the same for just vanilla javascript.

Ok, then you can start building the basic blocks ():

- login form
- user account page
- main page

And probably we would have a workshop on how to make user registration. That needs to be prepared. Because this could be interesting for other students as well.

Let's build it :+1:

**Comment by stankasvecova** [comment]
Fantastic!

Just one more question. I learnt in the meantime how to set up my registration to .php database (I mentioned it on the call once) because i thought that was the way to go forward. Since I have it almost ready, could I possibly use it?

I do want your workshop on registration badly however, and if there is an extra benefit to re-doing it through google OAuth+FireBase, then will happily re-do it.

**Comment by MrTim** [comment]
yes, sure, you can experiment with thing, we're not limiting you.
You can continue to work on it and just create pull request with all the changes and we'll take a look! As usual)

**Comment by BTBTravis** [comment]
Both user registration and video blocks / video blocks list features seem doable to me. 👍  

As @MrTim mentioned firebase + google cloud stuffs like cloud functions and their authentication service could work as a backend.

Or we could do a Node.js app in Heroku?

Or I could quickly write a simple python + flask + mongo backend to handle user reg and video blocks and you could focus on the frontend for now. Then write your own backend when you are ready for that learning after the course. 

I think it depends on what you want to learn and how much involvement from us you want.

**Comment by BTBTravis** [comment]
So I think we have settled on the app concept for the final project and the README has been updated in #2 . as for the backend we can figure that out in future issues
